d /opt/union/back/data 0700 union union -
d /opt/union/blog/data 0700 union union -
d /opt/union/blog/data/logs 0700 union union -
d /opt/union/ram/data 0700 union union -
d /opt/union/ram/data/logs 0700 union union -
d /opt/union/union/data 0700 union union -
d /opt/union/blog/source 1775 root union -
d /opt/union/blog/source/dist 0755 union union -
d /opt/union/blog/source/dist.next 0755 union union -
d /opt/union/blog/source/dist.previous 0755 union union -
d /opt/union/blog/source/.astro 0700 union union -
d /opt/union/blog/source/node_modules/.vite 0700 union union -
e /opt/union/blog/data/logs - - - 90d
